### PR TITLE
use 2 GB RAM config

### PR DESCRIPTION
**Pull request by visi0nary**
Change-Id: I56402912c7518a734c5c681c9e7da7c4d8822ae0

### CODE REVIEW

**Comment by visi0nary** [comment]
Your current config uses the 1 GB RAM heap config which means apps are killed to early. Here's a fix :)

**Comment by mdeejay** [comment]
ARK Benefit has only 1 Gb RAM

**Comment by visi0nary** [comment]
Oh, I'm sorry then. I have the Elephone Trunk and I thought they were exactly the same. My bad!

**Comment by mdeejay** [comment]
yeah. difference only RAM size

**Pull request closed without merging**
